imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }
    - { resource: @RsIssuesBundle/Resources/config/es_mapping.yml }

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"

jms_serializer:
    metadata:
        directories:
            issues:
                namespace_prefix: "Rs\\Issues"
                path: "@RsIssuesBundle/Resources/config/serializer/issues"
