dashboard:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::base.html.twig'

rs_issues:
    resource: "@RsIssuesBundle/Resources/config/routing.xml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"